### PR TITLE
Update URLs and copy to match project name

### PR DESCRIPTION
**Pull request by reentim**
`bundle` is the suggested Pathogen package directory, so I changed that too.

### CODE REVIEW

**Comment by kevinoid** [comment]
Thanks for the fixes and your interest in the project.  `~/.vim/bundles` is definitely in error that should be changed to `~/.vim/bundle`, but I'm not clear on why "checker" would be preferable to "linter".  "linter" is about 150x more common in the ALE sources (from `grep | wc`) and is the only term used in its README.md.  Can you explain?

**Comment by kevinoid** [comment]
Ha.  I just realized I named this repository `ale-detect-checkers` and used `ale-detect-linters` in the docs.  I'm dense.  A holdover from the Syntastic version.  Thanks for catching that.

I may make the opposite change and rename this repo `ale-detect-linters` to match the ALE terminology (it is the L in ALE after all).  Any objection?

**Comment by reentim** [comment]
No objections. I thought, based on this project name, that ALE had changed its terminology to be in terms of generic 'checkers', but it seems it's still just linters and fixers... so `ale-detect-linters` makes sense to me.

Incidentally, I came here looking for a Ruby solution. Do you have plans to add that? If not, are PRs welcome? — and if so, would adapting `python.vim` be a good start?

**Comment by kevinoid** [comment]
I just renamed this repo and merged your fix to use `~/.vim/bundle` for Pathogen.  Let me know if I missed anything.

> Incidentally, I came here looking for a Ruby solution. Do you have plans to add that? If not, are PRs welcome? — and if so, would adapting python.vim be a good start?

Absolutely!  PRs would be gladly accepted.  Copying `autoload/ale/detect/python.vim` to `autoload/ale/detect/ruby.vim`, replacing the detection logic, then adding `ruby` to `plugin/ale-detect-linters.vim` should work well.  You may want to use https://github.com/syngan/vim-vimlint while editing, but I don't mind cleaning up lint issues post-merge.  Don't worry about it if using it is difficult.

The only reason I haven't done it yet is that I don't use Ruby often, so it hasn't been a priority and I'm not familiar with linter configuration conventions.  However, if you aren't comfortable writing VimL, but willing to write pseudo-code detection logic, feel free to open an issue with a pseudo-code description and I'll implement it.

Thanks again,
Kevin

**Pull request closed without merging**
